/*
 * This file is generated by jOOQ.
 */
package com.mykolas.ignitismessagetask.jooqdatabase;


import com.mykolas.ignitismessagetask.jooqdatabase.tables.Messages;
import com.mykolas.ignitismessagetask.jooqdatabase.tables.Users;
import com.mykolas.ignitismessagetask.jooqdatabase.tables.records.MessagesRecord;
import com.mykolas.ignitismessagetask.jooqdatabase.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in APP.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessagesRecord> CONSTRAINT_1 = Internal.createUniqueKey(Messages.MESSAGES, DSL.name("CONSTRAINT_1"), new TableField[] { Messages.MESSAGES.ID }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_4 = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_4"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MessagesRecord, UsersRecord> AUTHOR_ID_FK = Internal.createForeignKey(Messages.MESSAGES, DSL.name("AUTHOR_ID_FK"), new TableField[] { Messages.MESSAGES.AUTHOR_ID }, Keys.CONSTRAINT_4, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<MessagesRecord, UsersRecord> RECEIVER_ID_FK = Internal.createForeignKey(Messages.MESSAGES, DSL.name("RECEIVER_ID_FK"), new TableField[] { Messages.MESSAGES.RECEIVER_ID }, Keys.CONSTRAINT_4, new TableField[] { Users.USERS.ID }, true);
}
