/*
 * This file is generated by jOOQ.
 */
package com.mykolas.ignitismessagetask.jooqdatabase;


import com.mykolas.ignitismessagetask.jooqdatabase.tables.Messages;
import com.mykolas.ignitismessagetask.jooqdatabase.tables.Users;


/**
 * Convenience access to all tables in APP.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>APP.MESSAGES</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>APP.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
